version: '3'

services:
  rails:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    ports:
     - 3000:3000
    env_file:
      - .env

  mysql:
    image: mysql:8.0.23
    platform: linux/x86_64
    command:
      [
        "--sql_mode=",
        "--max_allowed_packet=64M",
        "--default-authentication-plugin=mysql_native_password",
      ]
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: "mysqladmin ping -h localhost -u root || exit 1"
      interval: 1s
      timeout: 10s
      retries: 5

volumes:
  db-data:
  bundle:
