version: '3'
x-services:
  &rails-service
  volumes:
    - .:/app:cached
    - ~/.ssh:/root/.ssh:cached
    - ~/.aws:/root/.aws:cached
    - bundle:/bundle:cached
  ports:
    - 3000:3000
  env_file:
    - .env

services:
  rails:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: server
    image: rails
    profiles:
      - backend
    <<: *rails-service

  rails-test:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: test
    image: rails-test
    depends_on:
      - mysql
      - redis
    profiles:
      - rails-test
    <<: *rails-service

  redis:
    image: redis:6.2.7-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: "redis-cli ping || exit 1"
      interval: 1s
      timeout: 3s
      retries: 5
    profiles:
      - rails-test
      - backend

  mysql:
    image: mysql:8.0.23
    platform: linux/x86_64
    command:
      [
        "--sql_mode=",
        "--max_allowed_packet=64M",
        "--default-authentication-plugin=mysql_native_password",
      ]
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: "mysqladmin ping -h localhost -u root || exit 1"
      interval: 1s
      timeout: 10s
      retries: 5
    profiles:
      - rails-test
      - backend

volumes:
  db-data:
  bundle:

networks:
  default:
    name: rails
