version: '3'

services:
  rails:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    ports:
     - 3000:3000
    env_file:
      - .env

  mysql:
    image: mysql:8.0.23
    platform: linux/x86_64
    ports:
      - 3306:3306
    volumes:
      - file-share-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: 'rails'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
    healthcheck:
      test: "mysqladmin ping -h localhost -u root || exit 1"
      interval: 1s
      timeout: 10s
      retries: 5

volumes:
  file-share-data:
  bundle:
